# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "hoe", "~>3.4", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe-doofus", "~>1.0", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.5", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-travis", "~>1.2", :group => [:development, :test]
gem "minitest", "~>4.5", :group => [:development, :test]
gem "nokogiri", "~>1.5", :group => [:development]
gem "rake", "~>10.0", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "rubyforge", ">=2.0.4", :group => [:development, :test]

# vim: syntax=ruby
