#! /usr/bin/env rake
#--
# MIME::Types for Ruby
#   http://rubyforge.org/projects/mime-types/
#   Copyright 2003 - 2005 Austin Ziegler.
#   Licensed under a MIT-style licence.
#
# $Id$
#++
require 'meta_project'
require 'rake/gempackagetask'
require 'rake/contrib/xforge'
require 'rake/clean'

require 'gmailer'

require 'archive/tar/minitar'
require 'zlib'

$LOAD_PATH.unshift('lib')

require 'mime/types'

DISTDIR = "mime-types-#{MIME::Types::VERSION}"
TARDIST = "../#{DISTDIR}.tar.gz"

$release_date = nil
$release_date = Time.parse(ENV['RELEASE_DATE']) if ENV['RELEASE_DATE']

task :test do |t|
  require 'test/unit/testsuite'
  require 'test/unit/ui/console/testrunner'

  runner = Test::Unit::UI::Console::TestRunner

  $LOAD_PATH.unshift('tests')
  $stderr.puts "Checking for test cases:" if t.verbose
  Dir['tests/tc_*.rb'].each do |testcase|
    $stderr.puts "\t#{testcase}" if t.verbose
    load testcase
  end

  suite = Test::Unit::TestSuite.new("MIME::Types")

  ObjectSpace.each_object(Class) do |testcase|
    suite << testcase.suite if testcase < Test::Unit::TestCase
  end

  runner.run(suite)
end

spec = eval(File.read("mime-types.gemspec"))
spec.version = MIME::Types::VERSION
desc "Build the RubyGem for MIME::Types"
task :gem => [ :test ]
Rake::GemPackageTask.new(spec) do |g|
  g.need_tar    = false
  g.need_zip    = false
  g.package_dir = ".."
end

desc "Build the MIME::Types manual.pdf"
task :manual do
  PDF::TechBook.run %w(-z)
end

desc "Build a MIME::Types .tar.gz distribution."
task :tar => [ TARDIST ]
file TARDIST => [ :test ] do |t|
  current = File.basename(Dir.pwd)
  Dir.chdir("..") do
    begin
      files = %W(bin/**/* lib/**/* tests/**/* ChangeLog README LICENCE
                 setup.rb pre-setup.rb)
      files = FileList[files.map { |file| File.join(current, file) }].to_a
      files.map! do |dd|
        ddnew = dd.gsub(/^#{current}/, DISTDIR)
        mtime = $release_date || File.stat(dd).mtime
        if File.directory?(dd)
          { :name => ddnew, :mode => 0755, :dir => true, :mtime => mtime }
        else
          if dd =~ %r{bin/}
            mode = 0755
          else
            mode = 0644
          end
          data = File.open(dd, "rb") { |ff| ff.read }
          { :name => ddnew, :mode => mode, :data => data, :size => data.size,
            :mtime => mtime }
        end
      end

      ff = File.open(t.name.gsub(%r{^\.\./}o, ''), "wb")
      gz = Zlib::GzipWriter.new(ff)
      tw = Archive::Tar::Minitar::Writer.new(gz)

      files.each do |entry|
        if entry[:dir]
          tw.mkdir(entry[:name], entry)
        else
          tw.add_file_simple(entry[:name], entry) { |os| os.write(entry[:data]) }
        end
      end
    ensure
      tw.close if tw
      if gz
        gz.finish
        gz.close
      end
    end
  end
end
task TARDIST => [ :test ]

desc "Build the RDoc documentation for MIME::Types"
task :docs do
  require 'rdoc/rdoc'
  rdoc_options = %w(--title MIME::Types --main README --line-numbers)
  files = FileList[*%w(README LICENCE ChangeLog bin/**/*.rb lib/**/*.rb)]
  rdoc_options += files.to_a
  RDoc::RDoc.new.document(rdoc_options)
end

desc "Build everything."
task :default => [ :tar, :gem ]
