name: Release

on:
  push:
    branches:
      - main
    paths:
      - lib/mime/types/version.rb

  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - lib/mime/types/version.rb

  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository == 'mime-types/ruby-mime-types' && (github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged))

    runs-on: ubuntu-latest
    environment: release

    env:
      rubygems_release_gem: true

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            fulcio.sigstore.dev:443
            github.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            rubygems.org:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true

      - id: rubygems
        run: |
          ruby -e \
            'print "version=", Gem::Specification.load(ARGV[0]).rubygems_version, "\n"' \
            mime-types.gemspec >>"${GITHUB_OUTPUT}"

      - uses: ruby/setup-ruby@e5ac7b085f6e63d49c8973eb0c6e04d876b881f1 # v1.230.0
        with:
          bundler-cache: false
          ruby-version: ruby

      - name: Install dependencies
        run: |
          gem update --system="${RUBYGEMS_VERSION}"
          bundle install --jobs 4 --retry 3
        env:
          RUBYGEMS_VERSION: ${{ steps.rubygems.outputs.version }}

      - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1.1.1
