name: Publish docs

on:
  workflow_dispatch:

  workflow_call:

permissions: {}

concurrency:
  group: publish-docs-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish_docs:
    name: Publish docs from main
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: read
      pages: write    # Publish documentation to pages
      id-token: write # Publish documentation to pages

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - id: rubygems
        run: |
          ruby -e \
            'print "version=", Gem::Specification.load(ARGV[0]).rubygems_version, "\n"' \
            mime-types.gemspec >>"${GITHUB_OUTPUT}"

      - uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          bundler-cache: false
          ruby-version: ruby

      - name: Install dependencies
        run: |
          gem update --system="${RUBYGEMS_VERSION}"
          bundle install --jobs 4 --retry 3
        env:
          RUBYGEMS_VERSION: ${{ steps.rubygems.outputs.version }}

      - name: Build documentation
        run: |
          rake docs

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: doc

      - name: Deploy documentation
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
