name: Release

on:
  push:
    branches:
      - main
    paths:
      - lib/mime/types/version.rb

  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - lib/mime/types/version.rb

  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release mime-types
    if: github.repository == 'mime-types/ruby-mime-types' && (github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged))

    runs-on: ubuntu-latest
    environment: release

    env:
      rubygems_release_gem: true

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            fulcio.sigstore.dev:443
            github.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            rubygems.org:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true

      - id: rubygems
        run: |
          ruby -e \
            'print "version=", Gem::Specification.load(ARGV[0]).rubygems_version, "\n"' \
            mime-types.gemspec >>"${GITHUB_OUTPUT}"

      - uses: ruby/setup-ruby@cf7216d52fba1017929b4d7162fabe2b30af5b49 # v1.262.0
        with:
          bundler-cache: false
          ruby-version: ruby

      - name: Install dependencies
        run: |
          gem update --system="${RUBYGEMS_VERSION}"
          bundle install --jobs 4 --retry 3
        env:
          RUBYGEMS_VERSION: ${{ steps.rubygems.outputs.version }}

      - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1.1.1
